// Copyright (c) Jupyter Development Team.
// Distributed under the terms of the Modified BSD License.

import { IDisposable } from '@lumino/disposable';

import { getNotebookShim, NotebookShim } from './notebook';
import { getApp, getTracker } from './shimcontext';

/**
 * A classic action: a handler plus display metadata.
 */
export interface IClassicAction {
  handler: (env: any, event?: any) => any;
  help?: string;
  icon?: string;
  help_index?: string;
}

/**
 * Translate a classic shortcut string (e.g. `'ctrl-shift-h'` or `'d,d'`)
 * to Lumino keystrokes.
 *
 * @param shortcut - The classic shortcut
 * @returns One Lumino keystroke per chord step
 */
export function translateShortcut(shortcut: string): string[] {
  return shortcut.split(',').map(step => {
    const parts = step.trim().split('-');
    const key = parts.pop() ?? '';
    const modifiers = parts.map(
      part => Private.MODIFIERS[part.toLowerCase()] ?? part
    );
    return [...modifiers, Private.translateKey(key)].join(' ');
  });
}

/**
 * Get the singleton keyboard manager shim.
 */
export function getKeyboardManagerShim(): KeyboardManagerShim {
  return Private.getOrCreate();
}

/**
 * Replica of the classic `Jupyter.keyboard_manager.actions`, backed by the
 * application command registry.
 */
export class ActionHandlerShim {
  /**
   * The environment passed to action handlers; `env.notebook` resolves to
   * the current notebook shim.
   */
  readonly env: any = {
    pager: null,
    quick_help: null,
    get notebook(): NotebookShim | null {
      const panel = getTracker().currentWidget;
      return panel ? getNotebookShim(panel) : null;
    }
  };

  /**
   * Register a classic action as an application command.
   *
   * @param action - The action object, or a bare handler function
   * @param name - The action name, autogenerated when omitted
   * @param prefix - The action prefix, defaults to `'auto'`
   * @returns The full action name, `'prefix:name'`
   */
  register(
    action: IClassicAction | ((env: any, event?: any) => any),
    name?: string,
    prefix?: string
  ): string {
    const normalized: IClassicAction =
      typeof action === 'function' ? { handler: action } : action;
    const actionName = name ?? 'autogenerated-' + String(normalized.handler);
    const full = (prefix ?? 'auto') + ':' + actionName;
    this._disposables.get(full)?.dispose();
    this._actions.set(full, normalized);
    this._disposables.set(
      full,
      getApp().commands.addCommand(full, {
        label: normalized.help || actionName,
        caption: normalized.help ?? '',
        iconClass: normalized.icon ? 'fa ' + normalized.icon : undefined,
        describedBy: { args: null },
        execute: () => normalized.handler(this.env)
      })
    );
    return full;
  }

  /**
   * Get a registered action by its full name.
   */
  get(name: string): IClassicAction | undefined {
    return this._actions.get(name);
  }

  /**
   * Whether an action with this full name is registered by the shim.
   */
  exists(name: string): boolean {
    return this._actions.has(name) || getApp().commands.hasCommand(remap(name));
  }

  /**
   * Invoke an action by name, or the mapped application command.
   */
  call(name: string, event?: any, env?: any): any {
    const action = this._actions.get(name);
    if (action) {
      return action.handler(env ?? this.env, event);
    }
    return getApp().commands.execute(remap(name));
  }

  /**
   * Resolve an action name: strings pass through, objects and functions
   * are registered, like in classic.
   */
  get_name(name_or_data: any): string {
    if (typeof name_or_data === 'string') {
      return name_or_data;
    }
    return this.register(name_or_data);
  }

  /**
   * Extend the handler environment, classic style.
   */
  extend_env(obj: any): void {
    Object.assign(this.env, obj);
  }

  private _actions = new Map<string, IClassicAction>();
  private _disposables = new Map<string, IDisposable>();
}

/**
 * Replica of the classic shortcut managers, backed by application
 * keybindings scoped to a notebook mode selector.
 */
export class ShortcutManagerShim {
  /**
   * Construct a shortcut manager for one CSS selector scope.
   */
  constructor(actions: ActionHandlerShim, selector: string) {
    this._actions = actions;
    this._selector = selector;
  }

  /**
   * Bind a classic shortcut to an action.
   *
   * @param shortcut - The classic shortcut string, e.g. `'ctrl-shift-h'`
   * @param data - A full action name, an action object, or a handler
   */
  add_shortcut(shortcut: string, data: any): void {
    const command = remap(this._actions.get_name(data));
    const binding = getApp().commands.addKeyBinding({
      keys: translateShortcut(shortcut),
      selector: this._selector,
      command
    });
    this._bindings.get(shortcut.toLowerCase())?.dispose();
    this._bindings.set(shortcut.toLowerCase(), binding);
  }

  /**
   * Bind several shortcuts at once.
   */
  add_shortcuts(data: { [shortcut: string]: any }): void {
    for (const shortcut of Object.keys(data)) {
      this.add_shortcut(shortcut, data[shortcut]);
    }
  }

  /**
   * Remove a shortcut previously added through this shim. Default
   * JupyterLab keybindings cannot be removed at runtime.
   */
  remove_shortcut(shortcut: string): void {
    const binding = this._bindings.get(shortcut.toLowerCase());
    if (!binding) {
      console.warn(
        `jupyterlab-unsafe-globals: cannot remove the shortcut '${shortcut}', it was not added by this shim`
      );
      return;
    }
    binding.dispose();
    this._bindings.delete(shortcut.toLowerCase());
  }

  private _actions: ActionHandlerShim;
  private _selector: string;
  private _bindings = new Map<string, IDisposable>();
}

/**
 * Replica of the classic `Jupyter.keyboard_manager`.
 */
export class KeyboardManagerShim {
  /**
   * The classic actions registry.
   */
  readonly actions = new ActionHandlerShim();

  /**
   * Command mode shortcuts.
   */
  readonly command_shortcuts = new ShortcutManagerShim(
    this.actions,
    '.jp-Notebook.jp-mod-commandMode:not(.jp-mod-readWrite) :focus:not(:read-write)'
  );

  /**
   * Edit mode shortcuts.
   */
  readonly edit_shortcuts = new ShortcutManagerShim(
    this.actions,
    '.jp-Notebook.jp-mod-editMode'
  );

  /**
   * No-op: Lumino scopes shortcuts through selectors, so the classic
   * global keyboard toggling is not needed.
   */
  enable(): void {
    /* no-op */
  }

  /**
   * No-op, see `enable`.
   */
  disable(): void {
    /* no-op */
  }

  /**
   * No-op, see `enable`.
   */
  register_events(): void {
    /* no-op */
  }

  /**
   * Switch the current notebook to edit mode.
   */
  edit_mode(): void {
    const panel = getTracker().currentWidget;
    if (panel) {
      panel.content.mode = 'edit';
    }
  }

  /**
   * Switch the current notebook to command mode.
   */
  command_mode(): void {
    const panel = getTracker().currentWidget;
    if (panel) {
      panel.content.mode = 'command';
    }
  }
}

/**
 * Map a classic builtin action name to its JupyterLab command id;
 * unknown names pass through unchanged.
 */
export function remap(name: string): string {
  return Private.BUILTIN_ACTIONS[name] ?? name;
}

/**
 * The namespace for module private data.
 */
namespace Private {
  /**
   * Get or create the singleton keyboard manager.
   */
  export function getOrCreate(): KeyboardManagerShim {
    if (!keyboardManager) {
      keyboardManager = new KeyboardManagerShim();
    }
    return keyboardManager;
  }

  let keyboardManager: KeyboardManagerShim | null = null;

  /**
   * Classic modifier names to Lumino modifiers.
   */
  export const MODIFIERS: { [name: string]: string } = {
    ctrl: 'Ctrl',
    shift: 'Shift',
    alt: 'Alt',
    meta: 'Cmd',
    cmd: 'Cmd',
    cmdtrl: 'Accel'
  };

  /**
   * Classic key names to Lumino key names.
   */
  const KEYS: { [name: string]: string } = {
    esc: 'Escape',
    space: 'Space',
    enter: 'Enter',
    return: 'Enter',
    tab: 'Tab',
    backspace: 'Backspace',
    up: 'ArrowUp',
    down: 'ArrowDown',
    left: 'ArrowLeft',
    right: 'ArrowRight',
    pageup: 'PageUp',
    pagedown: 'PageDown',
    home: 'Home',
    end: 'End',
    insert: 'Insert',
    delete: 'Delete',
    minus: '-',
    comma: ','
  };

  /**
   * Translate one classic key token to a Lumino key name.
   */
  export function translateKey(key: string): string {
    const lower = key.toLowerCase();
    if (KEYS[lower]) {
      return KEYS[lower];
    }
    if (/^f\d{1,2}$/.test(lower)) {
      return lower.toUpperCase();
    }
    return key.length === 1 ? key.toUpperCase() : key;
  }

  /**
   * The classic builtin action names extensions bind, mapped to the
   * JupyterLab command ids.
   */
  export const BUILTIN_ACTIONS: { [name: string]: string } = {
    'jupyter-notebook:run-cell': 'notebook:run-cell',
    'jupyter-notebook:run-cell-and-select-next':
      'notebook:run-cell-and-select-next',
    'jupyter-notebook:run-cell-and-insert-below':
      'notebook:run-cell-and-insert-below',
    'jupyter-notebook:run-all-cells': 'notebook:run-all-cells',
    'jupyter-notebook:save-notebook': 'docmanager:save',
    'jupyter-notebook:enter-edit-mode': 'notebook:enter-edit-mode',
    'jupyter-notebook:enter-command-mode': 'notebook:enter-command-mode',
    'jupyter-notebook:split-cell-at-cursor': 'notebook:split-cell-at-cursor',
    'jupyter-notebook:merge-cells': 'notebook:merge-cells',
    'jupyter-notebook:delete-cell': 'notebook:delete-cell',
    'jupyter-notebook:undo-cell-deletion': 'notebook:undo-cell-action',
    'jupyter-notebook:copy-cell': 'notebook:copy-cell',
    'jupyter-notebook:cut-cell': 'notebook:cut-cell',
    'jupyter-notebook:paste-cell-below': 'notebook:paste-cell-below',
    'jupyter-notebook:insert-cell-above': 'notebook:insert-cell-above',
    'jupyter-notebook:insert-cell-below': 'notebook:insert-cell-below',
    'jupyter-notebook:move-cell-up': 'notebook:move-cell-up',
    'jupyter-notebook:move-cell-down': 'notebook:move-cell-down',
    'jupyter-notebook:change-cell-to-code': 'notebook:change-cell-to-code',
    'jupyter-notebook:change-cell-to-markdown':
      'notebook:change-cell-to-markdown',
    'jupyter-notebook:change-cell-to-raw': 'notebook:change-cell-to-raw',
    'jupyter-notebook:restart-kernel': 'notebook:restart-kernel',
    'jupyter-notebook:interrupt-kernel': 'notebook:interrupt-kernel'
  };
}
